### PR TITLE
chore: wait for traefik namespace to be actually removed

### PR DESCRIPTION
**Pull request by kkaempf**
this is a copy & paste from deployments/workloads.go and partially
fixes issue #186

### CODE REVIEW

**Comment by kkaempf** [comment]
A lot of code below `deployments/` has similar patterns and is a prime candidate for refactoring. I don't have sufficient Go knowledge to do this myself :-/

**Comment by jimmykarily** [comment]
At some point we implemented this: https://github.com/SUSE/carrier/blob/main/deployments/minibroker.go#L88 `WaitForNamespaceMissing`. I think it could be used for both for Traefik and Workloads.

**Comment by kkaempf** [comment]
Or we close #186 and make it an explicit decision to uninstall as fast as possible

**Comment by jimmykarily** [comment]
We need #186 but we instead of uninstalling everything sequentially, we need to use go routines to parallelize what is possible. Some deployments need to be uninstalled before others but some others could be uninstalled in parallel.

**Comment by kkaempf** [comment]
Closing this PR due to above discussion.

**Pull request closed without merging**
