### PR TITLE
fix: Acceptance tests should run for PRs coming from forks

### PR DESCRIPTION
**Pull request by jimmykarily**
fix: Acceptance tests should run for PRs coming from forks  but Github secrets are not available in that case:
    
https://github.community/t/make-secrets-available-to-builds-of-forks/16166
    
We will make authenticated requests to GitHub only when the secrets are available.
We could use this instead:

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks
    
but it comes with a big warning.

### CODE REVIEW

**Review by andreas-kupries — COMMENTED** [review]
What are the security implications ?
Can this be limited to forks from a suse repository ?

**Review by andreas-kupries — DISMISSED** [review]
Ok.

**Comment by jimmykarily** [comment]
According to the first link in the PR description, their main concern was that someone could change the workflow in a PR in a way that allows them to simply access the secret. The second link describes the implementation Github chose afaict and it allows running the workflow for PRs but using the version of the workflow in the upstream repo. So a malicious contributor can't just simply print your secrets in public.

This change has the implication that we won't be able to test workflow changes by simply opening a PR (even our PRs). But we can't have everything I guess.

**Comment by jimmykarily** [comment]
Hmm I see a big warning here: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target

**Comment by jimmykarily** [comment]
Changed the code to use credentials when they are available and just make unauthenticated requests to Dockerhub when not.
The PR description is also updated.

**Review by andreas-kupries — APPROVED** [review]
ok

**Pull request merged**
